### ISSUE TITLE
grammar: function_call appearing in cond_clause

### ISSUE THREAD

**Issue by BlindingDark** [Tuxified/tree-sitter-elixir#22]
```elixir
cond do
  is_list([]) ->
    :list!
end
```

```yaml
source_file:
  cond:
    ERROR:
      pattern:
        variable:
    cond_clause:
      pattern:
        list:
      atom:
```
